option(ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(ENABLE_TSAN "Enable ThreadSanitizer" OFF)
option(VT_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(VT_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(VT_ENABLE_TSAN "Enable ThreadSanitizer" OFF)

if(VT_ENABLE_ASAN)
    set(ENABLE_ASAN ON)
endif()
if(VT_ENABLE_UBSAN)
    set(ENABLE_UBSAN ON)
endif()
if(VT_ENABLE_TSAN)
    set(ENABLE_TSAN ON)
endif()

function(set_sanitizer_flags target)
    get_target_property(target_type ${target} TYPE)
    set(is_static FALSE)
    if(target_type STREQUAL "STATIC_LIBRARY")
        set(is_static TRUE)
    endif()
    
    if(ENABLE_ASAN)
        target_compile_options(${target} PRIVATE -fsanitize=address)
        if(NOT is_static)
            target_link_options(${target} PRIVATE -fsanitize=address)
        endif()
    endif()
    
    if(ENABLE_UBSAN)
        target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-sanitize=function)
        if(NOT is_static)
            target_link_options(${target} PRIVATE -fsanitize=undefined -fno-sanitize=function)
        endif()
    endif()
    
    if(ENABLE_TSAN)
        if(ENABLE_ASAN)
            message(FATAL_ERROR "TSan and ASan cannot be enabled together")
        endif()
        target_compile_options(${target} PRIVATE -fsanitize=thread)
        if(NOT is_static)
            target_link_options(${target} PRIVATE -fsanitize=thread)
        endif()
    endif()
endfunction()
